### ISSUE TITLE
sketch file will not open when gutter and margin are set as vw units

### ISSUE THREAD

**Issue by Plummat** [IBM/css-gridish#13]

**Comment by seejamescode** [comment]
If anyone wants to take this on: The solution is convert all `vw` values in [these variables](https://github.com/IBM/css-gridish/blob/master/index.js#L169-L170). The `vw` values should be converted to `px` by doing `Xvw * .01 * breakpointSizeInPX`.

**Comment by Plummat** [comment]
@seejamescode on like 216, don't you simply need to pass in width to calculate the gutter, like you do when calculating margin?

**Comment by seejamescode** [comment]
Yeah, that needs to happen for any property that could be a `vw`. But we also need to add an argument for `parseUnit` that is breakpoint width. I do not believe Sketch will take a `%` unit.
