### ISSUE TITLE
Add scss for css grid-layout

### ISSUE THREAD

**Issue by nilesh-chavan** [IBM/css-gridish#17]
I was working on css-gridish. I face an Issue a grid-layout the fallback is only for flex but not for grid layout. I am working on it please help with grid-layout.

**Comment by seejamescode** [comment]
Hi @nilesh-chavan! We will not be supporting Internet Explorer’s implementation of CSS Grid due [to many constraints](https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/):

> You are unlikely to be able to simply rely on Autoprefixer to run and do the work for you. For example, if you have used auto placement for any item and then don’t set a position using the -ms properties, that item is going to stack up with any other unpositioned items in the first grid cell.

Please check out the article linked from Rachel Andrew for more information.

**Comment by nilesh-chavan** [comment]
Thanks for the Reply @seejamescode ,
        I want to add CSS class in grid-layout using scss.So, please help me with it..!

**Comment by seejamescode** [comment]
Like with the import directive? http://vanseodesign.com/css/sass-the-import-directive/

**Comment by nilesh-chavan** [comment]
can you update this code?
this code help to make "grid-column: span" your code is really awesome. I just want to add grid function.
please respond as soon as possible 
.#{$prefix}-grid__col--#{$currentName}--#{$i} {
            // If second-to-last media query, apply max-width instead of remaking classes in last media query
            @if $isSecondToLast {
              max-width: $maxColumnSize;
            }
            min-width: $columnSize;
            width: $columnSize;
            grid-column: span $i;
          }
