### ISSUE TITLE
Rem unit is not defined in resulting CSS

### ISSUE THREAD

**Issue by imkremen** [IBM/css-gridish#18]
Font size for root element (`<html>`) is not defined, it's mistakenly defined for `<body>`.

**Comment by seejamescode** [comment]
Thanks for catching that, @imkremen! Can you share an example of when this is necessary?

**Comment by imkremen** [comment]
For now css-gridish work incorrect. Check your bootstrap example in dev-tools, in json config rem unit set to 15px, but all calculated sizes based on 16px.
